# Generated by Django 6.0.3 on 2026-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
