# Generated by Django 6.0.3 on 2026-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_snapshot',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
